// Static and hardcoded, same reasoning as nflTeams.ts -- team names/ids essentially never
// change. Verified against GET https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/teams.
export const MLB_TEAMS: { id: string; name: string; abbr: string }[] = [
  { id: "29", name: "Arizona Diamondbacks", abbr: "ARI" },
  { id: "11", name: "Athletics", abbr: "ATH" },
  { id: "15", name: "Atlanta Braves", abbr: "ATL" },
  { id: "1", name: "Baltimore Orioles", abbr: "BAL" },
  { id: "2", name: "Boston Red Sox", abbr: "BOS" },
  { id: "16", name: "Chicago Cubs", abbr: "CHC" },
  { id: "4", name: "Chicago White Sox", abbr: "CWS" },
  { id: "17", name: "Cincinnati Reds", abbr: "CIN" },
  { id: "5", name: "Cleveland Guardians", abbr: "CLE" },
  { id: "27", name: "Colorado Rockies", abbr: "COL" },
  { id: "6", name: "Detroit Tigers", abbr: "DET" },
  { id: "18", name: "Houston Astros", abbr: "HOU" },
  { id: "7", name: "Kansas City Royals", abbr: "KC" },
  { id: "3", name: "Los Angeles Angels", abbr: "LAA" },
  { id: "19", name: "Los Angeles Dodgers", abbr: "LAD" },
  { id: "28", name: "Miami Marlins", abbr: "MIA" },
  { id: "8", name: "Milwaukee Brewers", abbr: "MIL" },
  { id: "9", name: "Minnesota Twins", abbr: "MIN" },
  { id: "21", name: "New York Mets", abbr: "NYM" },
  { id: "10", name: "New York Yankees", abbr: "NYY" },
  { id: "22", name: "Philadelphia Phillies", abbr: "PHI" },
  { id: "23", name: "Pittsburgh Pirates", abbr: "PIT" },
  { id: "25", name: "San Diego Padres", abbr: "SD" },
  { id: "26", name: "San Francisco Giants", abbr: "SF" },
  { id: "12", name: "Seattle Mariners", abbr: "SEA" },
  { id: "24", name: "St. Louis Cardinals", abbr: "STL" },
  { id: "30", name: "Tampa Bay Rays", abbr: "TB" },
  { id: "13", name: "Texas Rangers", abbr: "TEX" },
  { id: "14", name: "Toronto Blue Jays", abbr: "TOR" },
  { id: "20", name: "Washington Nationals", abbr: "WSH" },
];
