// Static and hardcoded, same reasoning as nflTeams.ts -- team names/ids essentially never
// change. Verified against GET https://site.api.espn.com/apis/site/v2/sports/basketball/nba/teams.
export const NBA_TEAMS: { id: string; name: string; abbr: string }[] = [
  { id: "1", name: "Atlanta Hawks", abbr: "ATL" },
  { id: "2", name: "Boston Celtics", abbr: "BOS" },
  { id: "17", name: "Brooklyn Nets", abbr: "BKN" },
  { id: "30", name: "Charlotte Hornets", abbr: "CHA" },
  { id: "4", name: "Chicago Bulls", abbr: "CHI" },
  { id: "5", name: "Cleveland Cavaliers", abbr: "CLE" },
  { id: "6", name: "Dallas Mavericks", abbr: "DAL" },
  { id: "7", name: "Denver Nuggets", abbr: "DEN" },
  { id: "8", name: "Detroit Pistons", abbr: "DET" },
  { id: "9", name: "Golden State Warriors", abbr: "GSW" },
  { id: "10", name: "Houston Rockets", abbr: "HOU" },
  { id: "11", name: "Indiana Pacers", abbr: "IND" },
  { id: "12", name: "LA Clippers", abbr: "LAC" },
  { id: "13", name: "Los Angeles Lakers", abbr: "LAL" },
  { id: "29", name: "Memphis Grizzlies", abbr: "MEM" },
  { id: "14", name: "Miami Heat", abbr: "MIA" },
  { id: "15", name: "Milwaukee Bucks", abbr: "MIL" },
  { id: "16", name: "Minnesota Timberwolves", abbr: "MIN" },
  { id: "3", name: "New Orleans Pelicans", abbr: "NOP" },
  { id: "18", name: "New York Knicks", abbr: "NYK" },
  { id: "25", name: "Oklahoma City Thunder", abbr: "OKC" },
  { id: "19", name: "Orlando Magic", abbr: "ORL" },
  { id: "20", name: "Philadelphia 76ers", abbr: "PHI" },
  { id: "21", name: "Phoenix Suns", abbr: "PHX" },
  { id: "22", name: "Portland Trail Blazers", abbr: "POR" },
  { id: "23", name: "Sacramento Kings", abbr: "SAC" },
  { id: "24", name: "San Antonio Spurs", abbr: "SAS" },
  { id: "28", name: "Toronto Raptors", abbr: "TOR" },
  { id: "26", name: "Utah Jazz", abbr: "UTA" },
  { id: "27", name: "Washington Wizards", abbr: "WAS" },
];
