// Static and hardcoded on purpose -- team names/ids essentially never change, so there's
// no reason to hit an API just to populate a name autocomplete. Verified against
// GET https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams (ESPN's team ids).
export const NFL_TEAMS: { id: string; name: string; abbr: string }[] = [
  { id: "22", name: "Arizona Cardinals", abbr: "ARI" },
  { id: "1", name: "Atlanta Falcons", abbr: "ATL" },
  { id: "33", name: "Baltimore Ravens", abbr: "BAL" },
  { id: "2", name: "Buffalo Bills", abbr: "BUF" },
  { id: "29", name: "Carolina Panthers", abbr: "CAR" },
  { id: "3", name: "Chicago Bears", abbr: "CHI" },
  { id: "4", name: "Cincinnati Bengals", abbr: "CIN" },
  { id: "5", name: "Cleveland Browns", abbr: "CLE" },
  { id: "6", name: "Dallas Cowboys", abbr: "DAL" },
  { id: "7", name: "Denver Broncos", abbr: "DEN" },
  { id: "8", name: "Detroit Lions", abbr: "DET" },
  { id: "9", name: "Green Bay Packers", abbr: "GB" },
  { id: "34", name: "Houston Texans", abbr: "HOU" },
  { id: "11", name: "Indianapolis Colts", abbr: "IND" },
  { id: "30", name: "Jacksonville Jaguars", abbr: "JAX" },
  { id: "12", name: "Kansas City Chiefs", abbr: "KC" },
  { id: "13", name: "Las Vegas Raiders", abbr: "LV" },
  { id: "24", name: "Los Angeles Chargers", abbr: "LAC" },
  { id: "14", name: "Los Angeles Rams", abbr: "LAR" },
  { id: "15", name: "Miami Dolphins", abbr: "MIA" },
  { id: "16", name: "Minnesota Vikings", abbr: "MIN" },
  { id: "17", name: "New England Patriots", abbr: "NE" },
  { id: "18", name: "New Orleans Saints", abbr: "NO" },
  { id: "19", name: "New York Giants", abbr: "NYG" },
  { id: "20", name: "New York Jets", abbr: "NYJ" },
  { id: "21", name: "Philadelphia Eagles", abbr: "PHI" },
  { id: "23", name: "Pittsburgh Steelers", abbr: "PIT" },
  { id: "25", name: "San Francisco 49ers", abbr: "SF" },
  { id: "26", name: "Seattle Seahawks", abbr: "SEA" },
  { id: "27", name: "Tampa Bay Buccaneers", abbr: "TB" },
  { id: "10", name: "Tennessee Titans", abbr: "TEN" },
  { id: "28", name: "Washington Commanders", abbr: "WSH" },
];
