// Static and hardcoded, same reasoning as nflTeams.ts -- team names/ids essentially never
// change. Verified against GET https://site.api.espn.com/apis/site/v2/sports/hockey/nhl/teams.
export const NHL_TEAMS: { id: string; name: string; abbr: string }[] = [
  { id: "25", name: "Anaheim Ducks", abbr: "ANA" },
  { id: "1", name: "Boston Bruins", abbr: "BOS" },
  { id: "2", name: "Buffalo Sabres", abbr: "BUF" },
  { id: "3", name: "Calgary Flames", abbr: "CGY" },
  { id: "7", name: "Carolina Hurricanes", abbr: "CAR" },
  { id: "4", name: "Chicago Blackhawks", abbr: "CHI" },
  { id: "17", name: "Colorado Avalanche", abbr: "COL" },
  { id: "29", name: "Columbus Blue Jackets", abbr: "CBJ" },
  { id: "9", name: "Dallas Stars", abbr: "DAL" },
  { id: "5", name: "Detroit Red Wings", abbr: "DET" },
  { id: "6", name: "Edmonton Oilers", abbr: "EDM" },
  { id: "26", name: "Florida Panthers", abbr: "FLA" },
  { id: "8", name: "Los Angeles Kings", abbr: "LAK" },
  { id: "30", name: "Minnesota Wild", abbr: "MIN" },
  { id: "10", name: "Montreal Canadiens", abbr: "MTL" },
  { id: "27", name: "Nashville Predators", abbr: "NSH" },
  { id: "11", name: "New Jersey Devils", abbr: "NJD" },
  { id: "12", name: "New York Islanders", abbr: "NYI" },
  { id: "13", name: "New York Rangers", abbr: "NYR" },
  { id: "14", name: "Ottawa Senators", abbr: "OTT" },
  { id: "15", name: "Philadelphia Flyers", abbr: "PHI" },
  { id: "16", name: "Pittsburgh Penguins", abbr: "PIT" },
  { id: "18", name: "San Jose Sharks", abbr: "SJS" },
  { id: "124292", name: "Seattle Kraken", abbr: "SEA" },
  { id: "19", name: "St. Louis Blues", abbr: "STL" },
  { id: "20", name: "Tampa Bay Lightning", abbr: "TBL" },
  { id: "21", name: "Toronto Maple Leafs", abbr: "TOR" },
  { id: "129764", name: "Utah Mammoth", abbr: "UTA" },
  { id: "22", name: "Vancouver Canucks", abbr: "VAN" },
  { id: "37", name: "Vegas Golden Knights", abbr: "VGK" },
  { id: "23", name: "Washington Capitals", abbr: "WSH" },
  { id: "28", name: "Winnipeg Jets", abbr: "WPG" },
];
