import type { SharpApiProvider, SharpApiRow } from "./types";

// Fixture rows, seeded from real SharpAPI responses captured during Phase 2.14
// implementation (see the plan file's "Verified this session" section) -- not invented.
// Covers one real game (Patriots @ Seahawks) across every confirmed market_type: full-game
// Game Lines, both confirmed segments, and all five confirmed player-prop stats, including
// a tiered second line on Receiving Yards to exercise the multi-line-per-player case.
const ROWS: SharpApiRow[] = [
  // Full-game Game Lines
  {
    id: "mock-ml-away",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "moneyline",
    selection: "NE Patriots",
    selection_type: "away",
    team_side: "away",
    odds_american: 150,
    line: null,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: false,
  },
  {
    id: "mock-ml-home",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "moneyline",
    selection: "SEA Seahawks",
    selection_type: "home",
    team_side: "home",
    odds_american: -180,
    line: null,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: false,
  },
  {
    id: "mock-spread-away",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "point_spread",
    selection: "NE Patriots +3.5",
    selection_type: "away",
    team_side: "away",
    odds_american: -115,
    line: 3.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: false,
    is_main_line: true,
  },
  {
    id: "mock-spread-home",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "point_spread",
    selection: "SEA Seahawks -3.5",
    selection_type: "home",
    team_side: "home",
    odds_american: -105,
    line: 3.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: false,
    is_main_line: true,
  },
  // Alternate spread lines -- exercises ResearchNumberedGrid's main-line preference (the
  // grid should still show the -115/-105 main line above, not one of these) and
  // ResearchAltLines' "more lines" section (which should show these two).
  {
    id: "mock-spread-away-alt",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "point_spread",
    selection: "NE Patriots +7",
    selection_type: "away",
    team_side: "away",
    odds_american: -220,
    line: 7,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: false,
    is_main_line: false,
  },
  {
    id: "mock-spread-home-alt",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "point_spread",
    selection: "SEA Seahawks -7",
    selection_type: "home",
    team_side: "home",
    odds_american: 175,
    line: 7,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: false,
    is_main_line: false,
  },
  {
    id: "mock-total-over",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "total_points",
    selection: "Over",
    selection_type: "over",
    odds_american: -110,
    line: 44.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: false,
  },
  {
    id: "mock-total-under",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "total_points",
    selection: "Under",
    selection_type: "under",
    odds_american: -110,
    line: 44.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: false,
  },
  // 1st-half segment (same shape, one confirmed segment)
  {
    id: "mock-1h-ml-home",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "1st_half_moneyline",
    selection: "SEA Seahawks",
    selection_type: "home",
    team_side: "home",
    market_segment: "1st_half",
    odds_american: -170,
    line: null,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: false,
  },
  // 1st-quarter segment -- exercises the "Quarters" grouped tab (distinct from "Halves")
  // and its inner sub-selector.
  {
    id: "mock-1q-spread-away",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "1st_quarter_point_spread",
    selection: "NE Patriots",
    selection_type: "away",
    team_side: "away",
    market_segment: "1st_quarter",
    odds_american: 124,
    line: 1.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: false,
  },
  // Player props -- Passing
  {
    id: "mock-prop-pass-yds-over",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "player_passing_yards",
    selection: "Over",
    selection_type: "over",
    odds_american: -115,
    line: 235.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: true,
    player_name: "Drake Maye",
    stat_category: "passing_yds",
  },
  {
    id: "mock-prop-pass-yds-under",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "player_passing_yards",
    selection: "Under",
    selection_type: "under",
    odds_american: -105,
    line: 235.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: true,
    player_name: "Drake Maye",
    stat_category: "passing_yds",
  },
  {
    id: "mock-prop-pass-td-over",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "player_passing_touchdowns",
    selection: "Over",
    selection_type: "over",
    odds_american: 133,
    line: 1.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: true,
    player_name: "Drake Maye",
    stat_category: "passing_tds",
  },
  {
    id: "mock-prop-pass-td-under",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "player_passing_touchdowns",
    selection: "Under",
    selection_type: "under",
    odds_american: -198,
    line: 1.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: true,
    player_name: "Drake Maye",
    stat_category: "passing_tds",
  },
  {
    id: "mock-prop-pass-yds-darnold-over",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "player_passing_yards",
    selection: "Over",
    selection_type: "over",
    odds_american: -110,
    line: 210.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: true,
    player_name: "Sam Darnold",
    stat_category: "passing_yds",
  },
  {
    id: "mock-prop-pass-yds-darnold-under",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "player_passing_yards",
    selection: "Under",
    selection_type: "under",
    odds_american: -110,
    line: 210.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: true,
    player_name: "Sam Darnold",
    stat_category: "passing_yds",
  },
  {
    id: "mock-prop-pass-td-darnold-over",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "player_passing_touchdowns",
    selection: "Over",
    selection_type: "over",
    odds_american: 104,
    line: 1.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: true,
    player_name: "Sam Darnold",
    stat_category: "passing_tds",
  },
  {
    id: "mock-prop-pass-td-darnold-under",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "player_passing_touchdowns",
    selection: "Under",
    selection_type: "under",
    odds_american: -138,
    line: 1.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: true,
    player_name: "Sam Darnold",
    stat_category: "passing_tds",
  },
  // Player props -- Receiving. Multiple real players per stat (matches the real API's
  // actual per-event coverage confirmed during implementation -- a single-player fixture
  // undersold how many props a real game actually has), plus a tiered second line on
  // Smith-Njigba to exercise the multiple-lines-per-player DK layout (see the reference
  // screenshots).
  // All 8 real players + real lines confirmed via a full 406-row per-event pull during
  // implementation (see the plan file) -- not hand-picked for balance. Real row counts
  // (16 rows / 8 players for receiving yards, etc.) confirmed both Over and Under are
  // posted for every player, not just Over -- an earlier pass here only carried Over into
  // the mock, which was itself a fixture gap, not anything true of the real API. A tiered
  // 4-line ladder is kept on Smith-Njigba's Over side only (real data only showed one line)
  // purely to exercise TierPager's chevron-paging path.
  ...[
    { player: "Jaxon Smith-Njigba", line: 85, over: -112, under: -108 },
    { player: "Hunter Henry", line: 35.5, over: -110, under: -110 },
    { player: "Demario Douglas", line: 20.5, over: -110, under: -110 },
    { player: "Cooper Kupp", line: 33.5, over: -115, under: -105 },
    { player: "A.J. Barner", line: 25.5, over: -108, under: -112 },
    { player: "Rashid Shaheed", line: 31.5, over: -105, under: -115 },
    { player: "A.J. Brown", line: 62.5, over: -112, under: -108 },
    { player: "Romeo Doubs", line: 37.5, over: -110, under: -110 },
  ].flatMap(({ player, line, over, under }, i): SharpApiRow[] => {
    const base = {
      sportsbook: "draftkings",
      event_id: "nfl_patriots_seahawks_2026-09-09_b3",
      home_team: "Seattle Seahawks",
      away_team: "New England Patriots",
      market_type: "player_receiving_yards",
      line,
      event_start_time: "2026-09-10T00:15Z",
      is_player_prop: true,
      player_name: player,
      stat_category: "receiving_yds",
    };
    return [
      { ...base, id: `mock-prop-rec-yds-${i}-over`, selection: "Over", selection_type: "over", odds_american: over },
      { ...base, id: `mock-prop-rec-yds-${i}-under`, selection: "Under", selection_type: "under", odds_american: under },
    ];
  }),
  // Smith-Njigba's three extra Over-only tiers (real data only showed one line) --
  // exercises TierPager's chevron-paging path once combined with the Over/Under pair above.
  ...[
    { line: 100, price: 156 },
    { line: 115, price: 210 },
    { line: 130, price: 320 },
  ].map(
    ({ line, price }, i): SharpApiRow => ({
      id: `mock-prop-rec-yds-njigba-extra-${i}`,
      sportsbook: "draftkings",
      event_id: "nfl_patriots_seahawks_2026-09-09_b3",
      home_team: "Seattle Seahawks",
      away_team: "New England Patriots",
      market_type: "player_receiving_yards",
      selection: "Over",
      selection_type: "over",
      odds_american: price,
      line,
      event_start_time: "2026-09-10T00:15Z",
      is_player_prop: true,
      player_name: "Jaxon Smith-Njigba",
      stat_category: "receiving_yds",
    }),
  ),
  // Cooper Kupp's real two-line tier (2.5, 3.5) is the one genuine alternate line
  // confirmed for receptions -- everyone else had exactly one, each with both sides.
  ...[
    { player: "Jaxon Smith-Njigba", line: 5.5, over: -120, under: -105 },
    { player: "Hunter Henry", line: 3.5, over: -110, under: -110 },
    { player: "Cooper Kupp", line: 2.5, over: -105, under: -120 },
    { player: "Demario Douglas", line: 1.5, over: -140, under: 110 },
    { player: "A.J. Brown", line: 4.5, over: -110, under: -110 },
    { player: "A.J. Barner", line: 2.5, over: -115, under: -110 },
    { player: "Rashid Shaheed", line: 2.5, over: -108, under: -117 },
    { player: "Romeo Doubs", line: 3.5, over: -110, under: -110 },
  ].flatMap(({ player, line, over, under }, i): SharpApiRow[] => {
    const base = {
      sportsbook: "draftkings",
      event_id: "nfl_patriots_seahawks_2026-09-09_b3",
      home_team: "Seattle Seahawks",
      away_team: "New England Patriots",
      market_type: "player_receptions",
      line,
      event_start_time: "2026-09-10T00:15Z",
      is_player_prop: true,
      player_name: player,
      stat_category: "receptions",
    };
    return [
      { ...base, id: `mock-prop-rec-${i}-over`, selection: "Over", selection_type: "over", odds_american: over },
      { ...base, id: `mock-prop-rec-${i}-under`, selection: "Under", selection_type: "under", odds_american: under },
    ];
  }),
  // Cooper Kupp's alternate reception line (3.5) -- Over-only, mirroring the real
  // alternate-line shape confirmed for spreads/totals earlier (alt lines don't always carry
  // a matching alternate on the other side).
  {
    id: "mock-prop-rec-kupp-alt-over",
    sportsbook: "draftkings",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "player_receptions",
    selection: "Over",
    selection_type: "over",
    odds_american: 130,
    line: 3.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: true,
    player_name: "Cooper Kupp",
    stat_category: "receptions",
  },
  // Player props -- Rushing, again with multiple real players, both sides each.
  ...[
    { player: "Kenneth Walker III", line: 62.5, over: -108, under: -112 },
    { player: "TreVeyon Henderson", line: 48.5, over: -110, under: -110 },
    { player: "Rhamondre Stevenson", line: 30.5, over: -110, under: -110 },
  ].flatMap(({ player, line, over, under }, i): SharpApiRow[] => {
    const base = {
      sportsbook: "draftkings",
      event_id: "nfl_patriots_seahawks_2026-09-09_b3",
      home_team: "Seattle Seahawks",
      away_team: "New England Patriots",
      market_type: "player_rushing_yards",
      line,
      event_start_time: "2026-09-10T00:15Z",
      is_player_prop: true,
      player_name: player,
      stat_category: "rushing_yds",
    };
    return [
      { ...base, id: `mock-prop-rush-yds-${i}-over`, selection: "Over", selection_type: "over", odds_american: over },
      { ...base, id: `mock-prop-rush-yds-${i}-under`, selection: "Under", selection_type: "under", odds_american: under },
    ];
  }),
  // TD Scorers -- player_touchdowns is a real Over/Under prop; first/last_touchdown_scorer
  // are real single-outcome "will this player score" markets (line: null, mapped to
  // Side.YES). All three confirmed real, is_player_prop and selection_type exactly as the
  // live vendor sends them (first/last_touchdown_scorer really do ship is_player_prop:
  // false despite having a player_name -- see categorize.ts's TD_SCORER_MARKETS comment).
  {
    id: "mock-prop-td-over",
    // Confirmed real via SharpAPI's events/{id}/markets catalog: player_touchdowns'
    // real book list is ballybet/fanduel/novig/rebet -- draftkings does not carry this
    // market for this game at all.
    sportsbook: "fanduel",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "player_touchdowns",
    selection: "Over",
    selection_type: "over",
    odds_american: 146,
    line: 1.5,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: true,
    player_name: "Drake Maye",
    stat_category: "touchdowns",
  },
  {
    id: "mock-first-td-stevenson",
    sportsbook: "fanduel",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "first_touchdown_scorer",
    selection: "Rhamondre Stevenson",
    selection_type: "other",
    odds_american: 800,
    line: null,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: false,
    player_name: "Rhamondre Stevenson",
    stat_category: "anytime_td",
  },
  {
    id: "mock-last-td-hollins",
    sportsbook: "fanduel",
    event_id: "nfl_patriots_seahawks_2026-09-09_b3",
    home_team: "Seattle Seahawks",
    away_team: "New England Patriots",
    market_type: "last_touchdown_scorer",
    selection: "Mack Hollins",
    selection_type: "other",
    odds_american: 2700,
    line: null,
    event_start_time: "2026-09-10T00:15Z",
    is_player_prop: false,
    player_name: "Mack Hollins",
    stat_category: "anytime_td",
  },
  // A real futures/specials row, unattached to any game (empty away_team) -- confirms
  // summarizeSchedule/groupRowsByGame drop these rather than surfacing an "NFL Specials"
  // fake game.
  {
    id: "mock-futures-mvp",
    sportsbook: "fanduel",
    event_id: "nfl__nflspecials_2026-08-31_b1",
    home_team: "NFL Specials",
    away_team: "",
    market_type: "mvp",
    selection: "Jameson Williams",
    selection_type: "outright",
    odds_american: 50000,
    line: null,
    event_start_time: "2026-08-31T11:50Z",
    is_player_prop: false,
  },
  // A second, lighter game -- exercises the day-grouped multi-game schedule list without
  // needing full prop coverage on every fixture game.
  {
    id: "mock2-ml-away",
    sportsbook: "draftkings",
    event_id: "nfl_49ers_rams_2026-09-14_b1",
    home_team: "Los Angeles Rams",
    away_team: "San Francisco 49ers",
    market_type: "moneyline",
    selection: "SF 49ers",
    selection_type: "away",
    team_side: "away",
    odds_american: -130,
    line: null,
    event_start_time: "2026-09-15T00:05Z",
    is_player_prop: false,
  },
  {
    id: "mock2-ml-home",
    sportsbook: "draftkings",
    event_id: "nfl_49ers_rams_2026-09-14_b1",
    home_team: "Los Angeles Rams",
    away_team: "San Francisco 49ers",
    market_type: "moneyline",
    selection: "LA Rams",
    selection_type: "home",
    team_side: "home",
    odds_american: 110,
    line: null,
    event_start_time: "2026-09-15T00:05Z",
    is_player_prop: false,
  },
  {
    id: "mock2-spread-away",
    sportsbook: "draftkings",
    event_id: "nfl_49ers_rams_2026-09-14_b1",
    home_team: "Los Angeles Rams",
    away_team: "San Francisco 49ers",
    market_type: "point_spread",
    selection: "SF 49ers -1.5",
    selection_type: "away",
    team_side: "away",
    odds_american: -110,
    line: -1.5,
    event_start_time: "2026-09-15T00:05Z",
    is_player_prop: false,
  },
  {
    id: "mock2-spread-home",
    sportsbook: "draftkings",
    event_id: "nfl_49ers_rams_2026-09-14_b1",
    home_team: "Los Angeles Rams",
    away_team: "San Francisco 49ers",
    market_type: "point_spread",
    selection: "LA Rams +1.5",
    selection_type: "home",
    team_side: "home",
    odds_american: -110,
    line: 1.5,
    event_start_time: "2026-09-15T00:05Z",
    is_player_prop: false,
  },
];

// Deterministic, offline implementation for development/testing -- mirrors
// lib/schedule/mockProvider.ts's/lib/rosters/mockProvider.ts's role for this layer. Mirrors
// the real provider's two-entry-point shape: a cheap schedule (moneyline rows only) and a
// full per-event fetch, rather than one dump of everything.
export function createMockSharpApiProvider(): SharpApiProvider {
  return {
    async listNflSchedule(): Promise<SharpApiRow[]> {
      return ROWS.filter((r) => r.market_type === "moneyline");
    },
    async getNflEventOdds(eventId: string): Promise<SharpApiRow[]> {
      return ROWS.filter((r) => r.event_id === eventId);
    },
  };
}
